#!/usr/bin/env bash

main() {
local app=$1
local startX=$2 startY=$3 endX=$4 endY=$5
osascript << EOF
tell application "$1"
  set bounds of front window to {$startX, $startY, $endX, $endY}
end tell
EOF
}
main $@
