#!/usr/bin/env bash

osascript << EOF
tell application "iTerm"
    activate
    set _current_session to current session of current window
    tell _current_session
        set columns to ${1:-120}
    end tell
end tell
EOF
