#!/usr/bin/env bash

main() {
  cd `dirname $0`
  local size=$1
  local sizes=('small' 'medium' 'large')
  [ -z "$size" ] && size=$(echo ${sizes[@]} | tr ' ' '\n' | fzf)
  case "$size" in
    'small' )
      ./column 120
      ./row 40
      ./transparency 0.3
      ;;
    'medium' )
      ./column 150
      ./row 55
      ./transparency 0.3
      ;;
    'large' )
      ./column 200
      ./row 80
      ./transparency 0.6
      ;;
    * )
      ;;
  esac
}
main $@
