#!/usr/bin/env bash

screen_bounds() {
osascript << EOF
use framework "Foundation"
use framework "AppKit"
use scripting additions
(current application's NSScreen's screens()'s valueForKey:"frame") as list
EOF
}

select_screen() {
  screen_bounds | tr ',' '\n' | xargs -n 4 | fzf --select-1 --prompt 'screen {x y width height}'
}

# 画面サイズを取得する際はメインウィンドウの左下がorigin、セットする際は左上がoriginとなる
main() {
  cd `dirname $0`
  local size=$1
  local sizes=('small' 'large')
  [ -z "$size" ] && size=$(echo ${sizes[@]} | tr ' ' '\n' | fzf)

  local width height startX startY endX endY
  case "$size" in
    'small' )
      read x y width height <<< "$(select_screen)"
      [ -z "$width" ] && return
      startX=$(echo "$width * 0.3" + $x | bc)
      endX=$(echo "$x * 2.5 + $width - $startX" | bc)
      if [ $(echo "$y > 0" | bc) -eq 1 ]; then
        startY=$(echo "$height * 0.2 - $height" | bc)
        endY=$(echo "-1 * $height * 0.2" | bc)
      else
        startY=$(echo "$height * 0.2" | bc)
        endY=$(echo "$height - $startY * 1.5" | bc)
      fi
      ./bounds 'iTerm' $startX $startY $endX $endY
      ;;
    'large' )
      read x y width height <<< "$(select_screen)"
      [ -z "$width" ] && return
      startX=$(echo "$width * 0.25" + $x | bc)
      endX=$(echo "$x * 2 + $width - $startX" | bc)
      if [ $(echo "$y > 0" | bc) -eq 1 ]; then
        startY=$(echo "$height * 0.1 - $height" | bc)
        endY=$(echo "-1 * $height * 0.1" | bc)
      else
        startY=$(echo "$height * 0.1" | bc)
        endY=$(echo "$height - $startY" | bc)
      fi
      ./bounds 'iTerm' $startX $startY $endX $endY
      ;;
    * )
      ;;
  esac
  ./transparency 0.4
}
main $@
